version: '3'

networks:
  beam-network:
    driver: bridge

services:

## Messaging & Streaming

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - beam-network      
      
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - beam-network

## Storage & DB  
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data      
    environment:
      MINIO_ACCESS_KEY: "$MINIO_ROOT_USER"
      MINIO_SECRET_KEY: "$MINIO_ROOT_PASSWORD"
    command: server /data --console-address ":9001"
    networks:
      - beam-network      


## UI
  minio-console:
    image: minio/console:v0.26.3
    ports:
      - "9090:9090"
    networks:
      - beam-network
    command: server
    environment:
      CONSOLE_MINIO_SERVER: http://minio:9000
    depends_on:
      - minio

## BEAM

  flink-master:
    image: bde2020/flink-master:1.14.5-hadoop3.2
    hostname: flink-master
    container_name: flink-master
    volumes:
      - /Users/michael_sun/IdeaProjects/data-eng-tech-assessment/source-data/pedestrian:/tmp
    networks:
      - beam-network
    ports:
      - "8082:8080"
      - "8083:8081" #UI

  flink-worker:
    image: bde2020/flink-worker:1.14.5-hadoop3.2
    hostname: flink-worker
    container_name: flink-worker
    volumes:
      - /Users/michael_sun/IdeaProjects/data-eng-tech-assessment/source-data/pedestrian:/tmp
    networks:
      - beam-network
    environment:
      - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master
      - FLINK_NUM_TASK_SLOTS=10
    depends_on:
        - flink-master

volumes:
  minio-data:
    driver: local
  cli:
    driver: local  